extern const char footer_html[] ;
const char name_footer_html[] PROGMEM = "/footer.html";
extern const unsigned int footer_html_len ;
extern const char header_html[] ;
const char name_header_html[] PROGMEM = "/header.html";
extern const unsigned int header_html_len ;
extern const char buttons_list_shtml[] ;
const char name_buttons_list_shtml[] PROGMEM = "/buttons_list.shtml";
extern const unsigned int buttons_list_shtml_len ;
extern const char buttons_shtml[] ;
const char name_buttons_shtml[] PROGMEM = "/buttons.shtml";
extern const unsigned int buttons_shtml_len ;
extern const char credits_shtml[] ;
const char name_credits_shtml[] PROGMEM = "/credits.shtml";
extern const unsigned int credits_shtml_len ;
extern const char index_shtml[] ;
const char name_index_shtml[] PROGMEM = "/index.shtml";
extern const unsigned int index_shtml_len ;
extern const char lights_shtml[] ;
const char name_lights_shtml[] PROGMEM = "/lights.shtml";
extern const unsigned int lights_shtml_len ;
extern const char sensors_list_shtml[] ;
const char name_sensors_list_shtml[] PROGMEM = "/sensors_list.shtml";
extern const unsigned int sensors_list_shtml_len ;
extern const char sensors_shtml[] ;
const char name_sensors_shtml[] PROGMEM = "/sensors.shtml";
extern const unsigned int sensors_shtml_len ;
extern const char set_pin_shtml[] ;
const char name_set_pin_shtml[] PROGMEM = "/set_pin.shtml";
extern const unsigned int set_pin_shtml_len ;
extern const char ok_txt[] ;
const char name_ok_txt[] PROGMEM = "/ok.txt";
extern const unsigned int ok_txt_len ;
extern const char index_js[] ;
const char name_index_js[] PROGMEM = "/index.js";
extern const unsigned int index_js_len ;
